### ISSUE TITLE
Revisions with all numeric characters result in int label type causing builds to fail

### ISSUE THREAD

**Issue by dustinvanbuskirk** [codefresh-io/k8s-blue-green-deployment#2]
Ran into an issue where CF_REVISION has all numeric characters and this caused an integer issue with the version label being passed to Kubernetes.

We need to look at that version value and if quotes are set then add these quotes.

**Comment by kostis-codefresh** [comment]
The blue/green functionality itself is correct. The example provided did not have quotes around the version metadata label and that caused problems if the user had version with just number.

I added quotes in the both the service and deployment and now numerical versions should work just fine. Change was in 417ea6000a088bcadf9d8c70dedee9890a77008b
